export const GET_ALL_SONGS = 'GET_ALL_SONGS';
export const ADD_SONG = 'ADD_SONG';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';



// Playlists types

export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS'
export const GET_PLAYLISTS_SONGS = 'GET_PLAYLISTS_SONGS'
export const ADD_PLAYLIST = 'ADD_PLAYLIST'
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const DELETE_SONG_FROM_PLAYLIST = 'DELETE_SONG_FROM_PLAYLIST' 
export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST'